const templates = {
  morning: [
    "Expect a {condition} morning with temperatures starting around {min}-{max}°C.",
    "The day begins {condition}, with early temperatures between {min}°C and {max}°C.",
    "Morning hours will be {condition}, ranging from {min} to {max}°C.",
    "Start your day with {condition} skies and comfortable {min}-{max}°C temperatures.",
    "Dawn breaks with {condition} conditions and temps around {min}°C, rising to {max}°C.",
    "Early risers will find {condition} weather with morning lows near {min}°C.",
    "The sunrise brings {condition} skies and pleasant {min}-{max}°C temperatures.",
  ],
  afternoon: [
    "By the afternoon, conditions will be {condition}, with highs near {max}°C.",
    "The afternoon looks {condition}, as temperatures climb toward {max}°C.",
    "Afternoon skies will be {condition}, with temps hovering between {min}-{max}°C.",
    "Midday brings {condition} weather with peak temperatures reaching {max}°C.",
    "The warmest part of the day features {condition} skies and {max}°C highs.",
    "Lunch time will be {condition} with temperatures peaking around {max}°C.",
    "Expect {condition} conditions throughout the afternoon with highs of {max}°C.",
  ],
  evening: [
    "During the evening, expect {condition}, with temperatures easing to {min}-{max}°C.",
    "The evening brings {condition}, and a {precip}% chance of rain.",
    "As night approaches, {condition} skies dominate, with temps cooling to {min}°C.",
    "Sunset hours feature {condition} weather as temperatures drop to {min}-{max}°C.",
    "The evening will be {condition} with comfortable {min}-{max}°C temperatures.",
    "As daylight fades, {condition} conditions persist with temps around {min}°C.",
    "Dinner time brings {condition} skies and cooling temperatures near {min}°C.",
  ],
  night: [
    "Overnight, temperatures will settle near {min}°C under {condition} skies.",
    "The night will remain {condition}, with lows dipping to around {min}°C.",
    "Skies overnight are expected to be {condition}, with temperatures falling to {min}°C.",
    "Sleep tight under {condition} skies with overnight lows around {min}°C.",
    "The late hours bring {condition} conditions and cool {min}°C temperatures.",
    "Nighttime will be {condition} with temperatures settling near {min}°C.",
    "Expect {condition} skies through the night as temps drop to {min}°C.",
  ],
  precipitation: [
    "There's a {precip}% chance of rain.",
    "Showers are possible with rain chances peaking at {precip}%.",
    "Scattered showers could develop, bringing a {precip}% chance of rainfall.",
    "Keep an umbrella handy with {precip}% rain probability.",
    "Precipitation chances stand at {precip}% throughout the day.",
    "Light showers may occur with a {precip}% likelihood of rain.",
    "Weather models suggest a {precip}% chance of wet conditions.",
  ],
};
